# Welcome to Jekyll!
#

# Site settings
title: David Watson
description: |
  Lecturer in Artificial Intelligence, King's College London
owner: David Watson
first_published: 2020
email: david.watson@kcl.ac.uk
#baseurl: "/site"
permalink: pretty
collections:
  publications:
  software:
