# Welcome to Jekyll!
#

# Site settings
title: David Watson
description: |
  Lecturer in Artificial Intelligence, King's College London
owner: David Watson
first_published: 2020
email: david.s.watson11@gmail.com
#baseurl: "/site"
permalink: pretty
collections:
  publications:
