# Welcome to Jekyll!
#

# Site settings
title: David Watson
description: |
  Doctoral Candidate, University of Oxford
  CTO and Co-Founder, ThermoAI
owner: David Watson
first_published: 2020
email: david.s.watson11@gmail.com
#baseurl: "/site"
permalink: pretty
collections:
  publications:
